# Generated by Django 4.1.1 on 2023-03-13 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit', models.IntegerField(blank=True, default=0)),
                ('name', models.CharField(blank=True, max_length=40)),
                ('courseCode', models.IntegerField(blank=True)),
                ('done', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(blank=True, max_length=40)),
                ('middle', models.CharField(blank=True, max_length=40)),
                ('last', models.CharField(blank=True, max_length=40)),
                ('home', models.CharField(blank=True, max_length=40)),
                ('gender', models.CharField(blank=True, max_length=40)),
                ('nationality', models.CharField(blank=True, max_length=40)),
                ('idCard', models.CharField(blank=True, max_length=40)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('telephone', models.CharField(blank=True, max_length=40)),
                ('city', models.CharField(blank=True, max_length=40)),
                ('zipCode', models.CharField(blank=True, max_length=40)),
                ('teacherId', models.IntegerField(blank=True, null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
                ('username', models.CharField(blank=True, max_length=40, null=True)),
                ('email', models.EmailField(blank=True, max_length=40)),
                ('password', models.CharField(blank=True, max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(blank=True, max_length=40)),
                ('middle', models.CharField(blank=True, max_length=40)),
                ('last', models.CharField(blank=True, max_length=40)),
                ('home', models.CharField(blank=True, max_length=40)),
                ('gender', models.CharField(blank=True, max_length=40)),
                ('nationality', models.CharField(blank=True, max_length=40)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('city', models.CharField(blank=True, max_length=40)),
                ('zipCode', models.CharField(blank=True, max_length=40)),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
                ('studentId', models.IntegerField(unique=True)),
                ('username', models.CharField(blank=True, max_length=40, null=True)),
                ('email', models.EmailField(blank=True, max_length=30)),
                ('password', models.CharField(blank=True, max_length=15)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='omorapp.session')),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField(blank=True)),
                ('done', models.IntegerField(default=0)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='omorapp.session')),
            ],
        ),
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('text', models.TextField(blank=True, max_length=500)),
                ('files', models.FileField(blank=True, null=True, upload_to='media/')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='omorapp.course')),
                ('semester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='omorapp.semester')),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='omorapp.session')),
            ],
        ),
        migrations.CreateModel(
            name='finalEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cgpa', models.CharField(blank=True, default='0.0', max_length=3)),
                ('semester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='omorapp.semester')),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='omorapp.session')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='omorapp.student')),
            ],
        ),
        migrations.CreateModel(
            name='courseEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cgpa', models.CharField(blank=True, default='0.0', max_length=4)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='omorapp.course')),
                ('semester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='omorapp.semester')),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='omorapp.session')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='omorapp.student')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='courseTeacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='omorapp.teacher'),
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='omorapp.semester'),
        ),
        migrations.AddField(
            model_name='course',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='omorapp.session'),
        ),
        migrations.AddField(
            model_name='course',
            name='student',
            field=models.ManyToManyField(blank=True, null=True, to='omorapp.student'),
        ),
    ]
