# Generated by Django 4.1.1 on 2023-03-13 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omorapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
