# Generated by Django 4.1.1 on 2023-03-15 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omorapp', '0006_notice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='typo',
        ),
        migrations.AddField(
            model_name='notice',
            name='student',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notice',
            name='teacher',
            field=models.IntegerField(default=0),
        ),
    ]
