# Generated by Django 4.1.1 on 2023-03-24 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('omorapp', '0008_attendance_student_alter_attendance_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='date',
        ),
    ]
