# Generated by Django 4.1.1 on 2023-03-25 15:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('omorapp', '0010_student_image_teacher_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='mailId',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
