# Generated by Django 4.1.1 on 2023-03-25 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omorapp', '0013_alter_mail_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
