# Generated by Django 4.1.1 on 2023-03-27 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omorapp', '0014_alter_mail_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='remarks',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
